apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: gameon
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30880
      name: webapp-1
  selector:
    app: gameon
    tier: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: webapp
    spec:
      containers:
      - image: gameontext/gameon-webapp
        name: webapp
        env:
          - name: service_map
            value : https://map:9443/map/v1/sites
          - name: service_room
            value : ws://room:9080/rooms
          - name: service_simpleroom
            value : ws://simpleroom:9090/rooms
          - name: GITHUB_APP_ID
            value : ''
          - name: GITHUB_APP_SECRET
            value : ''
          - name: TWITTER_CONSUMER_KEY
            value : ''
          - name: TWITTER_CONSUMER_SECRET
            value : ''
          - name: MAP_SERVICE_URL
            value : http://127.0.0.1:6379/map/map/v1/sites
          - name: PLAYER_SERVICE_URL
            value : http://127.0.0.1:6379/players/players/v1/accounts
          - name: COUCHDB_SERVICE_URL
            value : http://couchdb:5984
          - name: KAFKA_SERVICE_URL
            value : kafka:9092
          - name: FRONT_END_PLAYER_URL
            value : https://169.47.241.213:30443/players/v1/accounts
          - name: FRONT_END_SUCCESS_CALLBACK
            value : https://169.47.241.213:30443/#/login/callback
          - name: FRONT_END_FAIL_CALLBACK
            value : https://169.47.241.213:30443/#/game
          - name: FRONT_END_AUTH_URL
            value : https://169.47.241.213:30443/auth
          - name: GAMEON_MODE
            value : development
          - name: TARGET_PLATFORM
            value : local
          - name: SYSTEM_ID
            value : game-on.org
          - name: LICENSE
            value : accept
          - name: PROXY_DOCKER_HOST
            value : '169.47.241.213'
          - name: ADMIN_PASSWORD
            value : admin
          - name: WLP_SKIP_MAXPERMSIZE
            value : 'true'
          - name: WLP_OUTPUT_DIR
            value : /opt/ibm/wlp/usr/servers/
          - name: LOG_DIR
            value : /opt/ibm/wlp/usr/servers/defaultServer/logs
          - name: MAP_KEY
            value : fish
          - name: COUCHDB_USER
            value : mapUser
          - name: COUCHDB_PASSWORD
            value : myCouchDBSecret
          - name: A8_REGISTRY_URL
            value : http://registry:8080
          - name: A8_CONTROLLER_URL
            value : http://controller:8080
          - name: A8_CONTROLLER_POLL
            value : 5s
          - name: A8_CONTROLLER_POLL
            value : 5s
        ports:
        - containerPort: 8080
          name: webapp-1
        - containerPort: 80
          name: webapp-2
        - containerPort: 443
          name: webapp-3
