apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    app: gameon
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: gameon
    tier: es
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: es
    spec:
      containers:
      - image: elasticsearch
        name: es
        ports:
        - containerPort: 9200
          name: es