apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: gameon
spec:
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: gameon
    tier: kibana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: kibana
    spec:
      containers:
      - image: kibana
        name: kibana
        env:
        - name: ELASTICSEARCH_URL
          value: http://es:9200
        ports:
        - containerPort: 5601
          name: kibana