apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: gameon
spec:
  ports:
    - port: 8092
      protocol: TCP
      targetPort: 8092
  selector:
    app: gameon
    tier: logstash
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: logstash
    spec:
      containers:
      - image: logstash
        name: logstash
        command:
          - "logstash"
          - "--verbose" 
          - "-e" 
          - "input { beats {codec=>'json' port=>8092}} output {elasticsearch {hosts =>'es:9200' codec=>'json'} }"
        ports:
        - containerPort: 8092
          name: logstash