apiVersion: v1
kind: Service
metadata:
  name: swiftroom
  labels:
    app: gameon
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gameon
    tier: swiftroom
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swiftroom
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: swiftroom
    spec:
      containers:
      - image: anthonyamanse/sample-room-swift:3.0
        name: swiftroom
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keystore
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/resources/security
      volumes:
      - name: keystore
        persistentVolumeClaim:
          claimName: keystore-claim